### PR TITLE
Bump octia to clojure 1.8.0

### PR DESCRIPTION
**Pull request by rborer**
Also upgrade compojure and cheshire.

:pedantic added so that the build fails if dependencies does not converge.

Fixed :warn-on-reflection, moved inside :global-vars as it's the new way to go with recent leiningen versions.

### CODE REVIEW

**Comment by obohrer** [comment]
Merci ! :tada:

**Comment by rborer** [comment]
Happy to help :smile: when you have a sec, could you deploy it to clojars?

**Comment by obohrer** [comment]
Sorry for the delay - Should be done later today.
Cheers !

**Comment by rborer** [comment]
Cool, thanks in advance!

**Pull request merged**
